import Header from "@/components/header";
import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import "./globals.css";

const inter = Lato({ weight: ["400"], subsets: [] });

export const metadata: Metadata = {
  title: "Clean Hand - my sprzątamy ty odpoczywasz",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl">
      <body suppressHydrationWarning={true} className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
